### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters in position 229-230: character maps to <undefined>

### ISSUE THREAD

**Issue by Salari7** [langnatalie/JoPEQ#1]
**Hi,
I'm using python 3.9 via Spyder 5. 
When I run the code, I get the following error:**

Traceback (most recent call last):

  File "C:\Users\ .spyder-py3\FL\JoPEQ-main\main.py", line 34, in <module>
    textio.cprint(str(summary(global_model)))

  File "C:\Users\ .spyder-py3\FL\JoPEQ-main\utils.py", line 124, in cprint
    self.f.write(text + '\n')

  File "C:\Users\ Anaconda3\envs\FL\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]

UnicodeEncodeError: 'charmap' codec can't encode characters in position 229-230: character maps to <undefined>

**I was wondering if you know how to fix it.
Thanks in advance**

**Comment by Salari7** [comment]
> **Hi, I'm using python 3.9 via Spyder 5. When I run the code, I get the following error:**
> 
> Traceback (most recent call last):
> 
> File "C:\Users\ .spyder-py3\FL\JoPEQ-main\main.py", line 34, in textio.cprint(str(summary(global_model)))
> 
> File "C:\Users\ .spyder-py3\FL\JoPEQ-main\utils.py", line 124, in cprint self.f.write(text + '\n')
> 
> File "C:\Users\ Anaconda3\envs\FL\lib\encodings\cp1252.py", line 19, in encode return codecs.charmap_encode(input,self.errors,encoding_table)[0]
> 
> UnicodeEncodeError: 'charmap' codec can't encode characters in position 229-230: character maps to
> 
> **I was wondering if you know how to fix it. Thanks in advance**
